import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 375, height: 812 } });
await page.goto('http://localhost:3001/login', { waitUntil: 'networkidle' });
await page.getByPlaceholder(/email/i).first().fill('admin@example.com');
const pwd = page.locator('input[type="password"]').first();
await pwd.fill('Admin1234!');
await page.getByRole('button', { name: /sign in|login|continue/i }).first().click();
await page.waitForTimeout(3000);
if (!page.url().includes('/app')) await page.goto('http://localhost:3001/app', { waitUntil: 'networkidle' });
await page.waitForTimeout(1500);
await page.screenshot({ path: '/tmp/opencode/p1_app_mobile.png' });
const menuBtn = page.locator('button[aria-label="Open navigation menu"]').first();
console.log('hamburger visible:', await menuBtn.isVisible());
await menuBtn.click();
await page.waitForTimeout(700);
const drawer = page.locator('aside').last();
console.log('drawer translate:', await drawer.evaluate(el => getComputedStyle(el).translate));
console.log('drawer width:', await drawer.evaluate(el => el.getBoundingClientRect().width));
await page.screenshot({ path: '/tmp/opencode/p1_drawer_open.png' });
console.log('sign out visible:', await drawer.getByText('Sign out').first().isVisible());
await browser.close();
console.log('OK');
